config-version: 2

name: "marketing_attribution_metrics"
version: "0.1.0"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  marketing_attribution_metrics:
    +materialized: table

vars:
  marketing_attribution_metrics:
    segment_tracks: "{{ ref('segment__tracks') }}"
    segment_identifies: "{{ ref('segment__identifies') }}"
    hubspot_email_event: "{{ ref('stg_hubspot__email_event') }}"
    hubspot_email_campaign: "{{ ref('stg_hubspot__email_campaign') }}"
    hubspot_email_event_filter__in: "('OPEN', 'CLICK')" # add more hubspot events here, if needed
    hubspot_event_to_segment_event_time_interval: hour # change this to any `datediff` interval (hour, day, year, etc)
    hubspot_event_to_segment_event_time_value: 2 # interval value between segment events and hubspot events

  hubspot_source:
    hubspot_schema: fivetran_hubspot
    hubspot_service_enabled: false
    hubspot_sales_enabled: false

    hubspot_marketing_enabled: true
    hubspot_email_event_bounce_enabled: false
    hubspot_email_event_click_enabled: false
    hubspot_email_event_deferred_enabled: false
    hubspot_email_event_delivered_enabled: true
    hubspot_email_event_dropped_enabled: false
    hubspot_email_event_forward_enabled: false
    hubspot_email_event_opens_enabled: true
    hubspot_email_event_print_enabled: false
    hubspot_email_event_sent_enabled: true
    hubspot_email_event_spam_report_enabled: false
    hubspot_email_event_status_change_enabled: false

  hubspot_metrics:
    email_event: "ref('stg_hubspot__email_event')"
